### ISSUE TITLE
Fixing UI Navigation

### ISSUE THREAD

**Issue by k----n** [CMPUT301F15T10/Exchange#37]
Navigating through UI currently does not work  

So far the activity from launching is login which leads to nowhere

**Comment by k----n** [comment]
Login -> Home  

Works now

**Comment by k----n** [comment]
Navigation from Trade Manager mostly works (missing History)

**Comment by touqir14** [comment]
Trade History is basically a list of completed trades which will be displayed onto trade list layout . I am currently turning them into fragments so that one layout can be reused to display complete trades and ongoing trades

**Comment by k----n** [comment]
Basic app navigation for Inventory/Items now works
