### ISSUE TITLE
DataIO does not work on basic types. 

### ISSUE THREAD

**Issue by laingsoft** [CMPUT301F15T10/Exchange#49]
or actually at all...

**Comment by touqir14** [comment]
Can you explain what type you used and what error you are getting?

**Comment by laingsoft** [comment]
It accepts a list, but Gson forgets types and it doesn't cast properly. I wrote two methods to save my object that work for now. 

It is a problem with the typing system that you've used.

**Comment by touqir14** [comment]
It should work fine for Integer, Double, Long, String. It probably wont work if you use primitive types.
