### ISSUE TITLE
Limit Input Size

### ISSUE THREAD

**Issue by k----n** [CMPUT301F15T10/Exchange#51]
editText needs to be edited to limit input size to single line, multiline etc.

**Comment by touqir14** [comment]
what editText? android widget?

**Comment by k----n** [comment]
We need to set the limit of how long we want our strings, int, etc. to be

**Comment by touqir14** [comment]
We can declare a global final static variable indicating length inside the global environment class if we need to.

**Comment by k----n** [comment]
I just limited input size in the xml, which is sufficient
