### ISSUE TITLE
Bug: Issue with edit user profile

### ISSUE THREAD

**Issue by touqir14** [CMPUT301F15T10/Exchange#57]
Once you edit the user info, if you view the user profile, the changes are not reflected. This is caused as the user object loaded in the home activity is not updated as we are mainly passing json strings. My suggestion would be to use a single UI for viewing and editing personal info. For viewing, the default info will be shown. Or we could fix it by updating the original user object inside home activity.

**Comment by laingsoft** [comment]
This seems like it is a problem that should be dealt with when we do the user Persistence. It should be something to address when #60  is addressed.
