### ISSUE TITLE
Data is not stored between session

### ISSUE THREAD

**Issue by laingsoft** [CMPUT301F15T10/Exchange#60]
ye

**Comment by touqir14** [comment]
As of now, the app is designed in such a way that the data is held inside home activity and is passed to any other activities as json strings and also it will receive the strings back if the called activity has the ability to modify the data. So, I would suggest to handle the loading and saving stuffs inside the home activity. Before the home activity is destroyed, it can save the data. Just 1-2 extra lines of calls.
