### ISSUE TITLE
Design Issue regarding offline storage

### ISSUE THREAD

**Issue by touqir14** [CMPUT301F15T10/Exchange#67]
I thought a bit about what Charles pointed out during our group discussion on Model View Controller Architecture. It seems it would be better to include a controller. So, say for example now when you add a new book from the inventory activity, the data is not updated with our local storage. Only if you exit from inventory activity that the inventory object is sent back to the home activity from which the model can be updated. If instead we use controllers from our UI activities that can directly save the data to the model before exiting, it will be better as I believe this what our TA and prof are expecting. Also that means that the loading and saving has to be efficient as at one point the data can get big. What do you guys think about storage efficiency issue?

**Comment by laingsoft** [comment]
Storage efficiency doesn't matter at all in this course. I don't think they care at all. 

By this point I think Shida would have pointed it out if anything was wrong with our design. The only real issue I can see is downloading images separately from the rest of the database. 

And we do have a controller, DataIO can read and save states of the GlobalENV object wherever you want. 

Passing strings is kinda a stupid way of manipulating data, but at least it saves on R/W cycles, I guess. Either way, I don't think it's that big of an issue. Android can easily handle parsing multi-thousand line json objects, even if it doesn't do it well, we won't be graded on it. 

I suggest checking the Rubrik, it is quite liberal with grades
