### ISSUE TITLE
Inventory Activity

### ISSUE THREAD

**Issue by touqir14** [CMPUT301F15T10/Exchange#68]
Why is add Item menu selection calling edit Item activity? Edit item activity isnt really designed to create a new book, it just edits an already created book. @laingsoft

**Comment by laingsoft** [comment]
No idea. I don't think I changed it. 

It's fixed in the last commit anyway.

**Comment by touqir14** [comment]
I checked the commit that you made in the morning. That commit contained those changes.

**Comment by laingsoft** [comment]
Coolio. It doesn't matter. I probably edited the wrong line.

**Comment by touqir14** [comment]
Dont get me wrong. I was just trying to make you cautious.
